config/routes.rb
AuthenticationExample::Application.routes.draw do
  root :to => 'welcome#index'
  get '/sign_up', :to => "users#new", :as => :sign_up
  post '/users', :to => "users#create", :as => :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    flash[:success] = "Your User has been successfully created"
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthenticationExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Sign Up", sign_up_path %>

<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for @user do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password%>
    <%= form.text_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </p>
  <%= form.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>